satconfig: fix choice block defaults
We used to always use a choice block's default, even when one of the
choices were forced/selected. For example, this Kconfig fragment:

  choice
          prompt "Preemption Model"
          default PREEMPT_NONE

  config PREEMPT_NONE
          bool "No Forced Preemption (Server)"

  config PREEMPT_VOLUNTARY
          bool "Voluntary Kernel Preemption (Desktop)"

  config PREEMPT
          bool "Preemptible Kernel (Low-Latency Desktop)"

  endchoice

Together with this .satconfig:

  CONFIG_PREEMPT_VOLUNTARY=y

Would give the following error:

  error: unsatisfiable constraints
  clause: PREEMPT_VOLUNTARY and PREEMPT_NONE are mutual exclusive
  clause: <choice> default PREEMPT_NONE [=n] if y

Because it would try to set both PREEMPT_VOLUNTARY=y (from the
.satconfig) and PREEMPT_NONE=y (from the 'default PREEMPT_NONE').

Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>